### ISSUE TITLE
No item image is displayed in Canvas

### ISSUE THREAD

**Issue by boych83** [microsoft/bcsamples-takeorder#10]
Hi @andersgMSFT,

I created this sample following the steps in [Fork the Repository](https://github.com/microsoft/AL-Go/blob/PPPreview/Scenarios/TryPowerPlatformSamples.md).

Should the canvas app display image of an items?

![image](https://github.com/microsoft/bcsamples-takeorder/assets/9000967/7394f819-c437-490a-8237-9f31a2664dc7)
![image](https://github.com/microsoft/bcsamples-takeorder/assets/9000967/693fee79-1d78-488f-b1f8-523d3ae9305d)

Regards,
Bojan

**Comment by andersgMSFT** [comment]
Hi Bojan

Yes, it definitely should show the image inside the app :)

It looks like you did run the sample data generator, and the image is added to the item. 

Do the images show up in the menu/list view? 

Another thing I would like to see if to open the item in "edit-mode" (or maker-mode). And see if there are any issues.

If your fork is public we can take a look and see if there is anything that stands out 

/Anders

**Comment by boych83** [comment]
Hi Anders,

lmage is not visible anywhere within the canvas app.

Looks like I'm having trouble with resource 'itemsWithImage' (/businessCentralDemos/TakeOrder/beta). Other resources are ok.
Removing and adding the source back doesn't help either. No problems in Postman, tho.
![image](https://github.com/microsoft/bcsamples-takeorder/assets/9000967/d9cf665d-f788-40e4-9634-44f3323460f4)
![image](https://github.com/microsoft/bcsamples-takeorder/assets/9000967/f493a38c-5555-4324-a6f3-68b4426fa450)

Regards,
Bojan

**Comment by andersgMSFT** [comment]
Thanks! 

I'll take a look and get a back to you! :)

**Comment by boych83** [comment]
Ok, thanks.

In the meantime, I managed to get the app working with a sligty changed API page (itemsWithImage - picture field as a Base64 string) and a custom connector for the BusinessCentralDemos/TakeOrder/beta resource with slight changes to the Canvas app. I was able to add a data connection to a my custom connector.

**Comment by andersgMSFT** [comment]
Sorry for the slow response time!

We found a bug in the Power Platform connector, that causes issues with APIs starting with "items". 

It sounded like you might have already found a workaround. If not, changing the API name to something that does not start with "Items" should help fix the issue.

We're rolling out a fix for the connector and anticipate it will be live in about a week, so after that, all APIs should be functioning again.

Thanks for trying the sample and reporting the issue! If you have more questions or feedback, we are happy to hear them!

**Comment by boych83** [comment]
Thanks, np.

Just wanted to test ALM for PP and BC artifacts and discovered this issue.I'm transitioning from BC to work more on PP so I wanted this app to work and try different things. So I found a solution with my custom connector just because I wanted to learn and try more things with PP and custom connectors.

BR,
Bojan
