### ISSUE TITLE
How to do step no 4

### ISSUE THREAD

**Issue by Olwinz** [microsoft/bcsamples-takeorder#11]
Hello,

Could you please give a detailed step-by-step how to import solution to Power Apps using the downloaded file? Please describe if we need to zip some folder before importing to Power Apps.

Many thanks,
Olwin

**Comment by andersgMSFT** [comment]
Apologies for the slow response time! 

If you download "TakeOrder-main-PowerPlatformSolution-1.0.21.0" and unzip it. It should contain another zip file. This is the solutions file and can be imported using the Power Apps Solution tab and "Import solution"
