### ISSUE TITLE
Cant import powerapp

### ISSUE THREAD

**Issue by chajtus** [microsoft/bcsamples-takeorder#4]
When I want to import the canvas (TakeOrder.zip) there is an error: Something went wrong. Try again later.

There is no log, nothing, tried on two different tenants, I have environment maker role.

WarehouseHelper, the same.

**Comment by andersgMSFT** [comment]
Hey Chajtus 

Thanks for logging the issue! I just tried reproducing the import issue you describe in a clean Dev environment, but the solution imported without any issues for me. 

Can you share more information about error you are seeing? (what are the steps you take to import and maybe a screen shot of the error you are seeing)  

I have attached the steps I followed when importing - after you click import in the last screen shot, you'll be prompted to select a Business Central connection, just select an existing one or follow the steps to create a new connection: 
![step1](https://github.com/microsoft/bcsamples-takeorder/assets/90765077/84238de8-db20-492f-9481-15e9fa8be63b)
![step2](https://github.com/microsoft/bcsamples-takeorder/assets/90765077/a1c20599-b75d-46de-94ac-ddbc17c594ce)
![step3](https://github.com/microsoft/bcsamples-takeorder/assets/90765077/d828931e-1bc1-4985-87c3-0923a31aaf50)

**Comment by andersgMSFT** [comment]
it has been +30 days without activity on this issue, so we are marking it as closed. If the suggested workaround did not help and the issue still occurs, feel free to reach out an open another issue.
